kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: fleet-test
  namespace: fleet-default
spec:
  branch: {{.Values.gitRepo.branch}}
  repo: {{.Values.gitRepo.repo}}
  paths:
  - {{.Values.gitRepo.paths}}
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod